"""Infra, policy, and helper file contents generated by labctl init."""

from __future__ import annotations

INFRA_FILES: dict[str, str] = {}

INFRA_FILES["infra/README.md"] = """# Infrastructure stack

Generated by `labctl init` from documents 01–11.

All management listeners bind to `127.0.0.1`. Do not publish these ports.
Do not put API keys in these files — use `*.env` (gitignored) copied from
`*.env.example`.

| Path | Plane | Document |
|---|---|---|
| `lima/` | Execution | 02, 03 |
| `gateway/` | Model | 01, 03, 05 |
| `observability/` | AI observability | 06 |
| `mcp/` | Capability | 03, 04 |
| `aegis/` | Policy | 04 |
| `numbat/` | Agent visibility | 04, 05 |
| `instrumentation/` | Experiment observability | 06, 07 |
| `harness-router.yaml` | Control | 01, 05 |
| `../policies/` | Security | 04 |

Apply with:

```bash
./scripts/bin/labctl stack up --stack observability
./scripts/bin/labctl stack up --stack gateway
```

Both require a container runtime and `--apply`. Dry-run is the default for
compose changes that start processes.
"""

INFRA_FILES["infra/versions.env"] = """# Pin images here. Do not use floating :latest in scored experiments.
# Verify tags against upstream before a recorded run.

LIMA_BASE_IMAGE=https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img
LITELLM_IMAGE=ghcr.io/berriai/litellm:main-stable
PHOENIX_IMAGE=arizephoenix/phoenix:latest
OTEL_COLLECTOR_IMAGE=otel/opentelemetry-collector-contrib:0.110.0
"""

INFRA_FILES["infra/lima/minimal.yaml"] = """# Disposable experiment VM — profile: minimal
# Generated from profiles.yaml + 03-deployment-runbook.md
vmType: qemu
cpus: 2
memory: "2GiB"
disk: "12GiB"

# Explicitly empty. Never mount host home, credentials, or SSH keys.
mounts: []

containerd:
  system: false
  user: false

plain: false

images:
  - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img"
    arch: "x86_64"

# NAT only. Do not bridge onto the lab host's LAN.
networks:
  - lima: user-v2

ssh:
  localPort: 0
  loadDotSSHPubKeys: false
"""

INFRA_FILES["infra/lima/default.yaml"] = """# Disposable experiment VM — profile: default
vmType: qemu
cpus: 2
memory: "2GiB"
disk: "20GiB"
mounts: []
containerd:
  system: false
  user: false
images:
  - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img"
    arch: "x86_64"
networks:
  - lima: user-v2
ssh:
  localPort: 0
  loadDotSSHPubKeys: false
"""

INFRA_FILES["infra/lima/security-research.yaml"] = """# Disposable experiment VM — profile: security-research
# First used by experiments/go-install-001
vmType: qemu
cpus: 2
memory: "2GiB"
disk: "20GiB"
mounts: []
containerd:
  system: false
  user: false
images:
  - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img"
    arch: "x86_64"
networks:
  - lima: user-v2
ssh:
  localPort: 0
  loadDotSSHPubKeys: false
provision:
  - mode: system
    script: |
      #!/bin/bash
      set -euxo pipefail
      export DEBIAN_FRONTEND=noninteractive
      apt-get update -y
      apt-get install -y --no-install-recommends ca-certificates curl git golang-go strace tcpdump iproute2 iputils-ping dnsutils
"""

INFRA_FILES["infra/gateway/.env.example"] = """# Copy to infra/gateway/.env (gitignored). Never commit real keys.
OPENAI_API_KEY=
ANTHROPIC_API_KEY=
XAI_API_KEY=
LITELLM_MASTER_KEY=change-me-on-localhost-only
"""

INFRA_FILES["infra/gateway/litellm_config.yaml"] = """# Logical aliases from 01-deployment-architecture.md / 05-multi-agent-operating-model.md
# LiteLLM and OmniRoute are alternatives. This file is the LiteLLM option.

model_list:
  - model_name: cheap-code
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY
  - model_name: medium-code
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY
  - model_name: strong-reasoning
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY
  - model_name: premium-verifier
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY
  - model_name: long-context
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY
  - model_name: free
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY

general_settings:
  # Local lab only.
  telemetry: false
"""

INFRA_FILES["infra/gateway/docker-compose.yml"] = """# Model gateway — LiteLLM option. Bind localhost only.
# Alternative: OmniRoute (do not run both unless testing composition).

name: lab-gateway

services:
  litellm:
    image: ${LITELLM_IMAGE:-ghcr.io/berriai/litellm:main-stable}
    env_file:
      - .env
    environment:
      LITELLM_MASTER_KEY: ${LITELLM_MASTER_KEY:-}
    command: ["--config", "/app/config.yaml", "--host", "127.0.0.1", "--port", "4000"]
    volumes:
      - ./litellm_config.yaml:/app/config.yaml:ro
    ports:
      - "127.0.0.1:4000:4000"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
"""

INFRA_FILES["infra/observability/.env.example"] = """# Copy to infra/observability/.env if needed. No secrets required for local Phoenix.
PHOENIX_PORT=6006
OTEL_PORT=4317
"""

INFRA_FILES["infra/observability/otel-collector.yaml"] = """receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch: {}
  memory_limiter:
    check_interval: 1s
    limit_mib: 256

exporters:
  otlphttp:
    endpoint: http://phoenix:6006/v1/traces
    tls:
      insecure: true
  debug:
    verbosity: basic

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp, debug]
"""

INFRA_FILES["infra/observability/docker-compose.yml"] = """# AI observability — OpenTelemetry + Phoenix. Localhost only.
name: lab-observability

services:
  phoenix:
    image: ${PHOENIX_IMAGE:-arizephoenix/phoenix:latest}
    ports:
      - "127.0.0.1:6006:6006"
    restart: unless-stopped

  otel-collector:
    image: ${OTEL_COLLECTOR_IMAGE:-otel/opentelemetry-collector-contrib:0.110.0}
    command: ["--config", "/etc/otelcol/config.yaml"]
    volumes:
      - ./otel-collector.yaml:/etc/otelcol/config.yaml:ro
    ports:
      - "127.0.0.1:4317:4317"
      - "127.0.0.1:4318:4318"
    depends_on:
      - phoenix
    restart: unless-stopped
"""

INFRA_FILES["infra/mcp/mcp_config.json"] = """{
  "mcpServers": {
    "lab-readonly": {
      "command": "python3",
      "args": ["-m", "labctl", "mcp-readonly"],
      "env": {
        "LABCTL_TIER": "read"
      }
    }
  },
  "notes": [
    "Replace lab-readonly with an approved MCP server after security review.",
    "Tier 4 (sudo, host filesystem, SSH, cloud credentials) must be approval-gated.",
    "Do not point MCP at host credential directories."
  ]
}
"""

INFRA_FILES["infra/aegis/policy.yaml"] = """# Local policy gate (Aegis stand-in until the chosen product is wired).
# Document 04 — Security Model. Default deny for privileged tiers.

schema_version: "1.0"
mode: monitor
product: labctl-policy
not_the_product_boundary: true

tiers:
  read:
    default: allow
    examples: [cat, rg, jq, git-diff]
  project-write:
    default: allow
    workspace_only: true
  git:
    default: approval
  vm:
    default: controlled
  network:
    default: deny
  credentials:
    default: deny
  host-root:
    default: deny

rules:
  - id: DENY-HOST-CREDS
    action: deny
    match:
      path_contains: [".ssh", ".aws", ".gnupg", ".config/gh"]
  - id: DENY-SUDO
    action: deny
    match:
      command_prefix: ["sudo", "pkexec"]
  - id: DENY-UNRESTRICTED-MOUNT
    action: deny
    match:
      lima_mounts_nonempty: true
  - id: ALLOW-READ
    action: allow
    match:
      command_prefix: ["cat", "rg", "jq", "yq", "git"]
"""

INFRA_FILES["infra/numbat/config.yaml"] = """# Agent visibility event log (Numbat stand-in).
# Events are append-only JSONL. Do not put secrets in fields.

schema_version: "1.0"
product: labctl-events
mode: monitor
event_log: events/numbat.jsonl

capture:
  tool_calls: true
  commands: true
  sessions: true
  policy_decisions: true

redact:
  - "api_key"
  - "token"
  - "password"
  - "authorization"
  - "secret"
"""

INFRA_FILES["infra/harness-router.yaml"] = """# HarnessRouter — document 01 / 05. Preferred roles, not a security boundary.
schema_version: "1.0"

roles:
  planner: antigravity
  researcher: opencode
  builder: grok-build
  security-reviewer: goose
  executor: controlled
  forensics: opencode
  verifier: codex
  reporter: antigravity
  archivist: antigravity

models:
  cheap-code: cheap-code
  medium-code: medium-code
  strong-reasoning: strong-reasoning
  premium-verifier: premium-verifier
  long-context: long-context
  free: free

rules:
  - "Antigravity CLI is a first-class harness, not the security boundary."
  - "Independent verifier must not inherit unverified conclusions as facts."
  - "LiteLLM and OmniRoute are alternatives; do not stack them by default."
"""

INFRA_FILES["infra/instrumentation/start-capture.sh"] = r"""#!/usr/bin/env bash
# Start host-side capture helpers. Prefer running the real collectors inside the VM.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
EXP="${1:-}"
OUT="${ROOT}/evidence/${EXP:-ad-hoc}/raw"
mkdir -p "${OUT}"
echo "start-capture $(date -u +%Y-%m-%dT%H:%M:%SZ) exp=${EXP:-ad-hoc}" | tee "${OUT}/capture-start.txt"
echo "Implement VM-side collectors in experiments/<id>/capture.sh"
echo "Host captures are optional and must not include credential files."
"""

INFRA_FILES["infra/instrumentation/stop-capture.sh"] = r"""#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
EXP="${1:-}"
OUT="${ROOT}/evidence/${EXP:-ad-hoc}/raw"
mkdir -p "${OUT}"
echo "stop-capture $(date -u +%Y-%m-%dT%H:%M:%SZ) exp=${EXP:-ad-hoc}" | tee "${OUT}/capture-stop.txt"
"""

INFRA_FILES["policies/permission-tiers.yaml"] = """# From 04-security-model.md
schema_version: "1.0"
tiers:
  read:
    default: allow
    examples: [cat, rg, jq, git-diff]
  project-write:
    default: allow
    constraint: workspace-boundary
  git:
    default: approval
  vm:
    default: controlled
  network:
    default: deny
  credentials:
    default: deny
  host-root:
    default: deny
privileged_operations:
  - sudo
  - host-filesystem
  - ssh
  - cloud-credentials
  - network-reconfiguration
  - destructive-delete-outside-vm
"""

INFRA_FILES["policies/mount-denylist.yaml"] = """# Paths that must never be mounted into experiment VMs.
schema_version: "1.0"
deny:
  - "~/.ssh"
  - "~/.gnupg"
  - "~/.aws"
  - "~/.config/gh"
  - "~/.config/gcloud"
  - "/etc/shadow"
  - "/home"
  - "/"
rules:
  - "mounts: [] is the default for every Lima profile in this repository."
  - "Evidence export uses limactl copy, not a host bind mount."
"""

INFRA_FILES["blackboard/README.md"] = """# Blackboard

Shared state between agents (document 05, `blackboard-schema.md`).

Runtime files (`*.json`, `*.jsonl`) are gitignored. Examples below are
committed as `*.example.json`.

```text
blackboard/
├── state.example.json
├── plan.example.json
├── tasks.example.jsonl
├── findings.example.jsonl
└── evidence-index.example.json
```
"""

INFRA_FILES["blackboard/state.example.json"] = """{
  "schema": "blackboard-state/1.0",
  "experiment": "go-install-001",
  "status": "not-started",
  "current_role": "planner"
}
"""

INFRA_FILES["blackboard/plan.example.json"] = """{
  "schema": "blackboard-plan/1.0",
  "objective": "Observe a pinned Go install inside a disposable VM.",
  "hypothesis": "Process, filesystem, DNS and network events correlate with go module fetch.",
  "success_criteria": ["vm-executed", "evidence-hashed", "independently-verified"],
  "safety": ["no-host-credentials", "empty-mounts", "preserve-evidence-before-delete"]
}
"""

INFRA_FILES["blackboard/tasks.example.jsonl"] = """{"task_id":"T001","role":"planner","status":"completed","artifact":"plan.json"}
{"task_id":"T002","role":"security-reviewer","status":"pending","artifact":"security-review.json"}
"""

INFRA_FILES["blackboard/findings.example.jsonl"] = """{"finding_id":"F001","claim":"example","evidence":["analysis/network.json"],"confidence":0.0,"verified":false}
"""

INFRA_FILES["blackboard/evidence-index.example.json"] = """{
  "artifact": "network.pcap",
  "type": "pcap",
  "sha256": "replace-after-capture",
  "source": "tcpdump",
  "timestamp": "1970-01-01T00:00:00Z",
  "description": "packet capture during target command"
}
"""

SHELL_COMMON = r'''#!/usr/bin/env bash
# Shared host-side helpers. Sourced by experiment scripts on the lab host.
set -euo pipefail

lab_root() {
  local here="$1"
  (cd "$here" && while [[ ! -f LICENSE || ! -f AGENTS.md ]]; do
    cd ..
    if [[ "$(pwd)" == "/" ]]; then
      echo "labctl: repository root not found" >&2
      return 1
    fi
  done
  pwd)
}

log() { printf '[labctl] %s\n' "$*"; }
die() { printf '[labctl] ERROR: %s\n' "$*" >&2; exit 1; }

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "missing command: $1"
}

utc_now() { date -u +%Y-%m-%dT%H:%M:%SZ; }
'''

SHELL_EVIDENCE = r'''#!/usr/bin/env bash
# Hash a directory tree to manifests/evidence.sha256
hash_tree() {
  local src="$1"
  local dest="$2"
  mkdir -p "$(dirname "$dest")"
  (cd "$src" && find . -type f -print0 | sort -z | xargs -0 sha256sum) > "$dest"
  log "wrote $dest"
}
'''
