package main

import (
 "context"
 "encoding/json"
 "errors"
 "flag"
 "fmt"
 "os"
 "os/exec"
 "path/filepath"
 "strings"
 "time"

 policyengine "github.com/opposum0112/Cusimanse/internal/policy"
)

type Requirements struct { Execution string `json:"execution"`; OS string `json:"os"`; Workload string `json:"workload"`; Network string `json:"network"`; Instrumentation []string `json:"instrumentation"` }
type Policy struct { Enforcement string `json:"enforcement"`; RequiredChecks []string `json:"required_checks"` }
type Experiment struct { ID string `json:"id"`; Requirements Requirements `json:"requirements"`; Policy Policy `json:"policy"` }
type HostProfile struct { Kind string `json:"kind"`; ID string `json:"id"`; ComputeRecipe string `json:"compute_recipe"`; Capabilities struct { OS string `json:"os"`; ExecutionBoundaries []string `json:"execution_boundaries"`; NetworkModes []string `json:"network_modes"`; Instrumentation []string `json:"instrumentation"` } `json:"capabilities"`; Execution struct { AgentMayGenerateProvisioning bool `json:"agent_may_generate_provisioning"`; AgentMayGenerateInstrumentation bool `json:"agent_may_generate_instrumentation"` } `json:"execution"` }
type WorkloadProfile struct { Kind string `json:"kind"`; ID string `json:"id"`; RuntimeHandler string `json:"runtime_handler"`; Instrumentation string `json:"instrumentation"`; Requirements Requirements `json:"requirements"`; Fixture string `json:"fixture"`; AgentMayModify bool `json:"agent_may_modify"` }
type Registry struct { Hosts []string `json:"hosts"`; Workloads []string `json:"workloads"` }
func root() string { if configured:=os.Getenv("CUSIMANSE_ROOT"); configured!="" { return configured }; if wd,err:=os.Getwd(); err==nil { if _,err:=os.Stat(filepath.Join(wd,"recipes"));err==nil{return wd} }; exe,_:=os.Executable();return filepath.Clean(filepath.Join(filepath.Dir(exe),"../..")) }
func load[T any](ctx context.Context,dir,path string,out *T) error { cmd:=exec.CommandContext(ctx,"yq","-o=json",".",path);cmd.Dir=dir;b,err:=cmd.Output();if err!=nil{return fmt.Errorf("read %s: %w",path,err)};if err:=json.Unmarshal(b,out);err!=nil{return fmt.Errorf("parse %s: %w",path,err)};return nil }
func run(ctx context.Context,dir,name string,args ...string) error { cmd:=exec.CommandContext(ctx,name,args...);cmd.Dir=dir;cmd.Stdout=os.Stdout;cmd.Stderr=os.Stderr;return cmd.Run() }
func contains(xs []string,x string)bool{for _,v:=range xs{if v==x{return true}};return false}
func containsAll(have,need []string)bool{for _,n:=range need{if !contains(have,n){return false}};return true}
func matches(req Requirements,wp WorkloadProfile)bool{if req.Workload!=""&&wp.Requirements.Workload!=req.Workload{return false};if req.OS!=""&&wp.Requirements.OS!=req.OS{return false};if req.Execution!=""&&wp.Requirements.Execution!=req.Execution{return false};if req.Network!=""&&wp.Requirements.Network!=req.Network{return false};return containsAll(wp.Requirements.Instrumentation,req.Instrumentation)}
func resolve(ctx context.Context,dir,exp string)(string,string,error){var e Experiment;if err:=load(ctx,dir,filepath.Join("recipes/experiments",exp+".yaml"),&e);err!=nil{return "","",err};var r Registry;if err:=load(ctx,dir,"recipes/profiles/registry.yaml",&r);err!=nil{return "","",err};workload:="";for _,p:=range r.Workloads{var w WorkloadProfile;if err:=load(ctx,dir,p,&w);err!=nil{return "","",err};if w.Kind=="workload-profile"&&matches(e.Requirements,w){if workload!=""{return "","",fmt.Errorf("ambiguous workload profile for %s",exp)};workload=p}};if workload==""{return "","",fmt.Errorf("no workload profile matches %s",exp)};var w WorkloadProfile;if err:=load(ctx,dir,workload,&w);err!=nil{return "","",err};host:="";for _,p:=range r.Hosts{var h HostProfile;if err:=load(ctx,dir,p,&h);err!=nil{return "","",err};if h.Kind!="host-profile"||h.Capabilities.OS!=e.Requirements.OS{continue};if e.Requirements.Execution!=""&&!contains(h.Capabilities.ExecutionBoundaries,e.Requirements.Execution+"-vm"){continue};if e.Requirements.Network!=""&&!contains(h.Capabilities.NetworkModes,e.Requirements.Network){continue};if !containsAll(h.Capabilities.Instrumentation,e.Requirements.Instrumentation)||!containsAll(h.Capabilities.Instrumentation,w.Requirements.Instrumentation){continue};if h.Execution.AgentMayGenerateProvisioning||h.Execution.AgentMayGenerateInstrumentation{continue};if host!=""{return "","",errors.New("ambiguous host profile")};host=p};if host==""{return "","",fmt.Errorf("no host profile matches %s",exp)};return host,workload,nil}
func sessionID(exp,requested string)string{if requested!=""{return requested};return time.Now().UTC().Format("20060102T150405Z")+"-"+exp}
func policy(ctx context.Context,dir string,e Experiment,approved bool)error{engine:=policyengine.NewFileEngine(dir);if err:=engine.Validate();err!=nil{return fmt.Errorf("native policy validation: %w",err)};for _,action:=range e.Policy.RequiredChecks{d:=engine.Evaluate(action,approved);if err:=engine.Audit(d);err!=nil{return fmt.Errorf("audit policy %s: %w",action,err)};if d.Decision!="allow"{if d.Decision=="approval-required"&&!approved{return fmt.Errorf("policy check %s requires explicit approval",action)};return fmt.Errorf("policy check %s denied: %s",action,d.Reason)}};return nil}
func checkpoint(ctx context.Context,dir,sid,state string)error{return run(ctx,dir,"scripts/session.sh","checkpoint",sid,state)}
func provision(ctx context.Context,dir,exp,sid string,approved bool)(string,WorkloadProfile,error){hpPath,wpPath,err:=resolve(ctx,dir,exp);if err!=nil{return "",WorkloadProfile{},err};var e Experiment;var h HostProfile;var w WorkloadProfile;if err:=load(ctx,dir,filepath.Join("recipes/experiments",exp+".yaml"),&e);err!=nil{return "",w,err};if err:=load(ctx,dir,hpPath,&h);err!=nil{return "",w,err};if err:=load(ctx,dir,wpPath,&w);err!=nil{return "",w,err};if err:=policy(ctx,dir,e,approved);err!=nil{return "",w,err};if err:=run(ctx,dir,"scripts/session.sh","create",exp,"goose",sid);err!=nil{return "",w,err};for _,state:=range []string{"VALIDATED","PREFLIGHTED","PLANNED"}{if err:=checkpoint(ctx,dir,sid,state);err!=nil{return "",w,err}};if approved{if err:=checkpoint(ctx,dir,sid,"AWAITING_APPROVAL");err!=nil{return "",w,err};if err:=checkpoint(ctx,dir,sid,"APPROVED");err!=nil{return "",w,err}};vm:="cusimanse-"+sid;if err:=run(ctx,dir,"limactl","validate",filepath.Join(dir,h.ComputeRecipe));err!=nil{return "",w,err};if err:=run(ctx,dir,"limactl","start","--name="+vm,filepath.Join(dir,h.ComputeRecipe));err!=nil{return "",w,err};if err:=checkpoint(ctx,dir,sid,"PROVISIONED");err!=nil{return "",w,err};fmt.Printf("CAPABILITY provision: host=%s workload=%s vm=%s\n",h.ID,w.ID,vm);return vm,w,nil}
func execute(ctx context.Context,dir,vm,runDir string,w WorkloadProfile)error{if err:=os.MkdirAll(filepath.Join(runDir,"evidence"),0755);err!=nil{return err};collector:=`set -e; date -u +%Y-%m-%dT%H:%M:%SZ > /tmp/cusimanse-start-time; ps -ef > /tmp/cusimanse-process-before; ss -tunap > /tmp/cusimanse-network-before || true; find /workspace -xdev -type f -print 2>/dev/null | sort > /tmp/cusimanse-files-before || true; if command -v tcpdump >/dev/null && sudo -n true 2>/dev/null; then sudo -n tcpdump -i any -U -w /tmp/cusimanse-network.pcap >/tmp/cusimanse-tcpdump.log 2>&1 & echo $! > /tmp/cusimanse-tcpdump.pid; fi`;if err:=run(ctx,dir,"limactl","shell",vm,"--","bash","-lc",collector);err!=nil{return err};if w.Fixture!=""{fixture:=filepath.Base(w.Fixture);cmd:=exec.CommandContext(ctx,"bash","-lc",fmt.Sprintf("tar -C packages -cf - %s | limactl shell %s -- bash -lc 'mkdir -p /workspace/packages && tar -xf - -C /workspace/packages'",fixture,vm));cmd.Dir=dir;cmd.Stdout=os.Stdout;cmd.Stderr=os.Stderr;if err:=cmd.Run();err!=nil{return err}};var command string;switch w.RuntimeHandler{case "go-install":command="set -e; cd /workspace/packages/labprobe; strace -ff -o /tmp/cusimanse-strace go install .; command -v labprobe; labprobe";case "npm-install":command="set -e; node --version; npm --version; mkdir -p /tmp/npm-test; cd /tmp/npm-test; npm init -y; strace -ff -o /tmp/cusimanse-strace npm install lodash@4.17.21 --ignore-scripts";case "npm-lifecycle","npm-threat":command="set -e; node --version; npm --version; mkdir -p /tmp/npm-test; cd /tmp/npm-test; npm init -y; strace -ff -o /tmp/cusimanse-strace npm install /workspace/packages/npm-fixture; test -f /tmp/cusimanse-npm-lifecycle-marker";default:return fmt.Errorf("unsupported handler %q",w.RuntimeHandler)};out,err:=os.Create(filepath.Join(runDir,"evidence","workload.txt"));if err!=nil{return err};defer out.Close();cmd:=exec.CommandContext(ctx,"limactl","shell",vm,"--","bash","-lc",command);cmd.Dir=dir;cmd.Stdout=out;cmd.Stderr=out;return cmd.Run()}
func collect(ctx context.Context,dir,vm,sid string)error{finalize:=`if [ -s /tmp/cusimanse-tcpdump.pid ]; then kill "$(cat /tmp/cusimanse-tcpdump.pid)" 2>/dev/null || true; fi; date -u +%Y-%m-%dT%H:%M:%SZ > /tmp/cusimanse-end-time; ps -ef > /tmp/cusimanse-process-after; ss -tunap > /tmp/cusimanse-network-after || true; find /workspace -xdev -type f -print 2>/dev/null | sort > /tmp/cusimanse-files-after || true; sha256sum /tmp/cusimanse-strace* /tmp/cusimanse-network.pcap 2>/dev/null > /tmp/cusimanse-collector-hashes || true`;if err:=run(ctx,dir,"limactl","shell",vm,"--","bash","-lc",finalize);err!=nil{return err};runDir:=filepath.Join(dir,"runs",sid);copies:=map[string]string{"process.txt":"cat /tmp/cusimanse-process-before /tmp/cusimanse-process-after","network.txt":"cat /tmp/cusimanse-network-before /tmp/cusimanse-network-after","filesystem.txt":"cat /tmp/cusimanse-files-before /tmp/cusimanse-files-after","syscalls.txt":"cat /tmp/cusimanse-strace* 2>/dev/null","collector-hashes.txt":"cat /tmp/cusimanse-collector-hashes /tmp/cusimanse-tcpdump.log 2>/dev/null","lifecycle-marker.txt":"cat /tmp/cusimanse-npm-lifecycle-marker 2>/dev/null","timestamps.txt":"cat /tmp/cusimanse-start-time /tmp/cusimanse-end-time 2>/dev/null"};for name,command:=range copies{out,err:=os.Create(filepath.Join(runDir,"evidence",name));if err!=nil{return err};cmd:=exec.CommandContext(ctx,"limactl","shell",vm,"--","bash","-lc",command);cmd.Dir=dir;cmd.Stdout=out;cmd.Stderr=out;_ = cmd.Run();_ = out.Close()};return checkpoint(ctx,dir,sid,"EVIDENCE_COLLECTED")}
func roleSkillWrite(root string, r RoleSkillRegistry) error { files,err:=renderRoleSkillYaml(root,r); if err!=nil{return err}; for p,b:=range files { if err:=os.MkdirAll(filepath.Dir(filepath.Join(root,p)),0755);err!=nil{return err}; if err:=os.WriteFile(filepath.Join(root,p),[]byte(b),0644);err!=nil{return err} }; return nil }
func splitCSV(s string) []string { if strings.TrimSpace(s)=="" {return nil}; parts:=strings.Split(s,","); out:=make([]string,0,len(parts)); for _,p:=range parts {if x:=strings.TrimSpace(p);x!=""{out=append(out,x)}}; return out }
func manageRoleSkill(ctx context.Context, dir string, args []string) error { if len(args)<2{return errors.New("usage: capability skill|role list|upsert ...")}; kind,op:=args[0],args[1]; r,err:=loadRoleSkillRegistry(dir);if err!=nil{return err}; if op=="list" {if kind=="skill"{for _,s:=range r.Skills{fmt.Printf("%s v%d: %s\n",s.Name,s.Version,s.Description)}}else if kind=="role"{for _,x:=range r.Roles{fmt.Printf("%s v%d: skills=%s\n",x.Name,x.Version,strings.Join(x.Skills,","))}}else{return errors.New("unknown registry kind")};return nil}; if op!="upsert"{return errors.New("supported operations: list, upsert")}; fs:=flag.NewFlagSet(kind+" upsert",flag.ContinueOnError);name:=fs.String("name","","stable name");desc:=fs.String("description","","description");version:=fs.Int("version",1,"version");caps:=fs.String("capabilities","","comma-separated capability names");skills:=fs.String("skills","","comma-separated skill names");tools:=fs.String("tools","","comma-separated required tools");if err:=fs.Parse(args[2:]);err!=nil{return err};if *name==""||*desc==""{return errors.New("--name and --description are required")};if kind=="skill"{err=upsertSkill(dir,Skill{Name:*name,Version:*version,Description:*desc,Capabilities:splitCSV(*caps),RequiredTools:splitCSV(*tools)})}else if kind=="role"{err=upsertRole(dir,Role{Name:*name,Version:*version,Description:*desc,Skills:splitCSV(*skills),Capabilities:splitCSV(*caps)})}else{return errors.New("unknown registry kind")};if err!=nil{return err};r,err=loadRoleSkillRegistry(dir);if err!=nil{return err};if err:=roleSkillWrite(dir,r);err!=nil{return err};fmt.Printf("updated %s %s and regenerated dependent YAML\n",kind,*name);return nil}
func main(){approved:=flag.Bool("approved",false,"use after explicit researcher approval for approval-gated actions");flag.Parse();args:=flag.Args();if len(args)<1{fmt.Println("usage: cusimanse [--approved] <capability|resolve|run> ...");os.Exit(2)};dir:=root();ctx:=context.Background();switch args[0]{case "capability":if len(args)>=3&&(args[1]=="skill"||args[1]=="role"){if err:=manageRoleSkill(ctx,dir,args[1:]);err!=nil{fmt.Fprintln(os.Stderr,err);os.Exit(1)};return};if len(args)!=2||args[1]!="list"{os.Exit(2)};fmt.Println("resolve provision configure execute collect destroy run skill role");case "resolve":if len(args)!=2{os.Exit(2)};h,w,e:=resolve(ctx,dir,args[1]);if e!=nil{fmt.Fprintln(os.Stderr,e);os.Exit(1)};fmt.Printf("host_profile: %s\nworkload_profile: %s\n",h,w);case "run":if len(args)<2{os.Exit(2)};exp:=args[1];sid:="";if len(args)>2{sid=args[2]};sid=sessionID(exp,sid);vm,w,e:=provision(ctx,dir,exp,sid,*approved);if e!=nil{fmt.Fprintln(os.Stderr,e);os.Exit(1)};if e=checkpoint(ctx,dir,sid,"INSTRUMENTED");e!=nil{fmt.Fprintln(os.Stderr,e);os.Exit(1)};if e=checkpoint(ctx,dir,sid,"EXECUTING");e!=nil{fmt.Fprintln(os.Stderr,e);os.Exit(1)};runDir:=filepath.Join(dir,"runs",sid);if e=execute(ctx,dir,vm,runDir,w);e!=nil{_ = checkpoint(ctx,dir,sid,"FAILED");fmt.Fprintln(os.Stderr,e);os.Exit(1)};if e=collect(ctx,dir,vm,sid);e!=nil{fmt.Fprintln(os.Stderr,e);os.Exit(1)};if e=run(ctx,dir,"scripts/session.sh","hash",sid);e!=nil{fmt.Fprintln(os.Stderr,e);os.Exit(1)};fmt.Printf("CAPABILITY run: evidence collected and hashed at runs/%s\n",sid);fmt.Println("Agent next: analyze → independently verify → report → preserve → destroy");default:fmt.Fprintln(os.Stderr,"unsupported capability");os.Exit(2)}}
