package main

import("context";"errors";"fmt";"os";"os/exec";"path/filepath";"strings";"github.com/opposum0112/Cusimanse/internal/policy";"github.com/opposum0112/Cusimanse/internal/preflight";"github.com/opposum0112/Cusimanse/internal/validation")
func init(){if len(os.Args)<2{return};switch os.Args[1]{case "validate":mustHandleCLICommand(nativeValidate);case "preflight":mustHandleCLICommand(nativePreflight);case "policy":mustHandleCLICommand(nativePolicy);case "install":mustHandleCLICommand(handleInstall);case "test":mustHandleCLICommand(func(root string)error{return runExternal(root,"go","test","./...")});case "integration-test":mustHandleCLICommand(func(root string)error{return runExternal(root,"bash","./scripts/tests/integration.sh")});case "doctor":mustHandleCLICommand(func(root string)error{if err:=nativeValidate(root);err!=nil{return err};return nativePreflight(root)});case "tools":mustHandleCLICommand(func(root string)error{return runHelperArgs(root,"scripts/tools.sh",os.Args[2:]...)});case "session":mustHandleCLICommand(func(root string)error{return runHelperArgs(root,"scripts/session.sh",os.Args[2:]...)});case "learning":mustHandleCLICommand(func(root string)error{return runHelperArgs(root,"scripts/learningctl",os.Args[2:]...)});case "observability":mustHandleCLICommand(func(root string)error{return runHelperArgs(root,"scripts/observability.sh",os.Args[2:]...)});case "run-experiment":mustHandleCLICommand(func(root string)error{return runHelperArgs(root,"scripts/run-experiment.sh",os.Args[2:]...)})}}
type OperationalAPI struct{Command string;Helper string;Bootstrap bool}
func OperationalAPIs()[]OperationalAPI{return []OperationalAPI{{"install","scripts/install.sh",true},{"validate","native:validation",false},{"preflight","native:preflight",false},{"test","go test ./...",false},{"integration-test","scripts/tests/integration.sh",false},{"tools","scripts/tools.sh",false},{"session","scripts/session.sh",false},{"policy","native:policy",false},{"learning","scripts/learningctl",false},{"observability","scripts/observability.sh",false},{"run-experiment","scripts/run-experiment.sh",false}}}
func nativeValidate(root string)error{v:=validation.New(root);if err:=v.Project();err!=nil{return err};return v.NoMarker("filecite","README.md","docs",".agents","recipes","scripts")}
func nativePreflight(root string)error{r:=preflight.New(root).Check();if len(r.Missing)>0{return fmt.Errorf("preflight failed: %s",strings.Join(r.Missing,", "))};fmt.Printf("PREFLIGHT PASS: platform=%s deterministic host/profile checks passed\n",r.Platform);return nil}
func nativePolicy(root string)error{args:=append([]string{},os.Args[2:]...);command:="validate";action:="";approved:=false;for i:=0;i<len(args);i++{switch args[i]{case "show","validate","check","check-all","require","enforce","explain","audit":command=args[i];if (args[i]=="check"||args[i]=="require"||args[i]=="enforce"||args[i]=="explain")&&i+1<len(args){action=args[i+1];i++};case "--approved","--approve":approved=true;case "--file":i++}};e:=policy.NewFileEngine(root);if command=="validate"{return e.Validate()};if command=="show"{p,err:=e.Load();if err!=nil{return err};fmt.Printf("version: %d\npolicy_file: %s\n",p.Version,e.PolicyFile);return nil};if command=="audit"{b,err:=os.ReadFile(e.AuditFile);if os.IsNotExist(err){return nil};if err!=nil{return err};fmt.Print(string(b));return nil};if command=="check-all"{for _,a:=range []string{"credentials","mounts","vm","network","git-write","public-mcp","public-gateway","host-execution","network-reconfig"}{d:=e.Evaluate(a,approved);if err:=e.Audit(d);err!=nil{return err};fmt.Printf("%s: %s (%s)\n",a,d.Decision,d.Reason)};return nil};if action==""{return errors.New("policy command requires an action")};d:=e.Evaluate(action,approved);if err:=e.Audit(d);err!=nil{return err};fmt.Printf("%s: %s (%s)\n",d.Action,d.Decision,d.Reason);switch d.Decision{case "deny":return fmt.Errorf("policy denied %s",action);case "approval-required":return fmt.Errorf("approval required for %s",action)};return nil}
func mustHandleCLICommand(handler func(string)error){rootDir,err:=commandRoot(os.Args[2:]);if err!=nil{fmt.Fprintln(os.Stderr,err);os.Exit(2)};if err:=handler(rootDir);err!=nil{fmt.Fprintf(os.Stderr,"cusimanse: %v\n",err);os.Exit(1)};os.Exit(0)}
func commandRoot(args []string)(string,error){if configured:=os.Getenv("CUSIMANSE_ROOT");configured!=""{st,err:=os.Stat(configured);if err!=nil||!st.IsDir(){return "",fmt.Errorf("CUSIMANSE_ROOT is not a directory: %s",configured)};return configured,nil};for i:=0;i<len(args);i++{if args[i]=="--root"&&i+1<len(args){return filepath.Abs(args[i+1])}};if wd,err:=os.Getwd();err==nil{if _,err:=os.Stat(filepath.Join(wd,"recipes"));err==nil{return wd,nil}};return "",errors.New("repository root not found; run from the Cusimanse repository or set CUSIMANSE_ROOT")}
func runHelperArgs(root,rel string,args ...string)error{path:=filepath.Join(root,rel);st,err:=os.Stat(path);if err!=nil||st.IsDir(){return fmt.Errorf("helper unavailable: %s",path)};return runExternal(root,path,args...)}
func runExternal(root,name string,args ...string)error{cmd:=exec.CommandContext(context.Background(),name,args...);cmd.Dir,cmd.Stdout,cmd.Stderr,cmd.Stdin=root,os.Stdout,os.Stderr,os.Stdin;return cmd.Run()}
func handleInstall(root string)error{if _,err:=os.Stat(filepath.Join(root,"scripts/install.sh"));err!=nil{return fmt.Errorf("bootstrap installer missing: %w",err)};if _,err:=exec.LookPath("go");err!=nil{return errors.New("Go is not installed; run scripts/install.sh once to bootstrap Go and host dependencies")};if err:=runHelperArgs(root,"scripts/install.sh");err!=nil{return fmt.Errorf("bootstrap installation failed: %w",err)};bin:=filepath.Join(os.Getenv("HOME"),".local","bin","cusimanse");if custom:=os.Getenv("CUSIMANSE_BIN");custom!=""{bin=custom};if err:=os.MkdirAll(filepath.Dir(bin),0755);err!=nil{return err};tmp:=bin+".tmp";_ = os.Remove(tmp);if err:=runExternal(root,"go","build","-trimpath","-o",tmp,"./cmd/cusimanse");err!=nil{return fmt.Errorf("build cusimanse: %w",err)};if err:=os.Chmod(tmp,0755);err!=nil{return err};if err:=os.Rename(tmp,bin);err!=nil{return err};fmt.Printf("installed %s\n",bin);return nil}
