import { access, readdir, readFile } from "node:fs/promises";
import { join } from "node:path";
import { tool, type ToolSet } from "ai";
import { z, type ZodType } from "zod";
import type { ComputeProvider } from "../adapters/compute/types.js";
import type { FailClosedToolApproval } from "../policy/approval.js";
export interface LoadedSkill { id: string; version: string; description: string; instructions: string; capability: string; schema: ZodType; tool: ToolSet[string]; }
export async function loadValidatedSkills(root = join(process.cwd(), "skills", "validated"), compute?: ComputeProvider, approval?: FailClosedToolApproval): Promise<Record<string, ToolSet[string]>> { const result: Record<string, ToolSet[string]> = {}; let entries: string[]; try { entries = await readdir(root); } catch { return result; } for (const entry of entries.sort()) { if (entry.startsWith(".")) continue; const directory = join(root, entry); if (!(await exists(join(directory, "SKILL.md"))) || !(await exists(join(directory, "schema.json")))) continue; const skill = await loadSkill(directory, compute, approval); result[skill.id] = skill.tool; } return result; }
async function loadSkill(directory: string, compute?: ComputeProvider, approval?: FailClosedToolApproval): Promise<LoadedSkill> { const [instructions, schemaText] = await Promise.all([readFile(join(directory, "SKILL.md"), "utf8"), readFile(join(directory, "schema.json"), "utf8")]); const schema = jsonSchemaToZod(JSON.parse(schemaText) as unknown); const metadata = parseFrontMatter(instructions); const id = metadata.id ?? directory.split(/[\\/]/u).pop() ?? "skill"; const version = metadata.version ?? "1.0.0"; const description = metadata.description ?? id; const capability = metadata.capability ?? id; const execute = async (input: unknown): Promise<unknown> => { const parsed = schema.parse(input); if (!compute) return { skill: id, status: "validated", input: parsed }; const record = isRecord(parsed) ? parsed : {}; const command = typeof record.command === "string" ? record.command : "true"; const args = Array.isArray(record.args) ? record.args.filter((item): item is string => typeof item === "string") : []; if (approval) { const status = approval.evaluate(id, { ...record, capability, operationKind: "tool" }); if (status === "denied" || (typeof status === "object" && status.type === "denied")) throw new Error(`Tool denied by policy: ${id}`); if (status === "user-approval" || (typeof status === "object" && status.type === "user-approval")) throw new Error(`Tool requires operator approval: ${id}`); } return await compute.exec(command, args); }; return { id, version, description, instructions, capability, schema, tool: tool({ description: `${description}\n\n${instructions}`, inputSchema: schema, execute }) }; }
function parseFrontMatter(markdown: string): Record<string, string> { const result: Record<string, string> = {}; for (const line of markdown.split(/\r?\n/u).slice(0, 20)) { const match = line.match(/^([a-zA-Z][a-zA-Z0-9_-]*)\s*:\s*(.+)$/u); if (!match) continue; const key = match[1]; const value = match[2]; if (key && value) result[key] = value.trim().replace(/^['"]|['"]$/gu, ""); } return result; }
function jsonSchemaToZod(document: unknown): ZodType { if (!isRecord(document)) throw new Error("schema.json must be an object"); const type = document.type; if (type === "object") { const properties = isRecord(document.properties) ? document.properties : {}; const required = new Set(Array.isArray(document.required) ? document.required.filter((item): item is string => typeof item === "string") : []); const shape: Record<string, ZodType> = {}; for (const [key, value] of Object.entries(properties)) { const field = jsonSchemaToZod(value); shape[key] = required.has(key) ? field : field.optional(); } return z.object(shape).strict(); } if (type === "string") { const values = Array.isArray(document.enum) ? document.enum.filter((item): item is string => typeof item === "string") : []; return values.length ? z.enum(values as [string, ...string[]]) : z.string(); } if (type === "number") return z.number(); if (type === "integer") return z.number().int(); if (type === "boolean") return z.boolean(); if (type === "array") return z.array(document.items === undefined ? z.unknown() : jsonSchemaToZod(document.items)); throw new Error(`Unsupported JSON Schema type: ${String(type)}`); }
function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value); }
async function exists(path: string): Promise<boolean> { try { await access(path); return true; } catch { return false; } }
