id: default
backend: qemu
vm_type: qemu
cpus: 2
memory: 2GiB
disk: 20GiB
image:
  location: https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img
  arch: x86_64
network: user-v2
mounts: []
ssh:
  load_dot_ssh_pub_keys: false
  local_port: 0
provision_packages:
  - ca-certificates
  - curl
  - git
  - iproute2
  - iputils-ping
  - dnsutils
