#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
mkdir -p "$HOME/.config/cusimanse"
log(){ printf '%s\n' "$*"; }
if command -v python3 >/dev/null 2>&1; then
  python3 -m pip install --user litellm || log 'LiteLLM: NOT_DEPLOYED'
else
  log 'LiteLLM: NOT_DEPLOYED (python3 unavailable)'
fi
if command -v npm >/dev/null 2>&1; then
  npm install -g omniroute || log 'OmniRoute: NOT_DEPLOYED'
else
  log 'OmniRoute: NOT_DEPLOYED (npm unavailable; install Node.js/npm and rerun)'
fi
cat > "$HOME/.config/cusimanse/litellm.yaml" <<'EOF'
# Generated by Cusimanse. Provider credentials remain environment-only.
model_list: []
router_settings:
  routing_strategy: simple-shuffle
  fallbacks: []
EOF
cat > "$HOME/.config/cusimanse/omniroute.yaml" <<'EOF'
# Generated by Cusimanse. Provider credentials remain environment-only.
providers: []
localhost_only: true
port: 20128
EOF
log "Gateway configuration written to $HOME/.config/cusimanse/{litellm,omniroute}.yaml"
